POST http://localhost:4000/auth/signup
Content-Type: application/json
x-api-key: your-api-key-2
accept-version: 1.0.0

{
    "email": "user@example.com",
    "socialProvider": "google",
    "socialId": "123456789"
}
