export enum TouriiBackendConstants {
    USER_REPOSITORY_TOKEN = 'USER_REPOSITORY_TOKEN',
    CONTEXT_PROVIDER_TOKEN = 'CONTEXT_PROVIDER_TOKEN',
    STORY_REPOSITORY_TOKEN = 'STORY_REPOSITORY_TOKEN',
    QUEST_REPOSITORY_TOKEN = 'QUEST_REPOSITORY_TOKEN',
    MODEL_ROUTE_REPOSITORY_TOKEN = 'MODEL_ROUTE_REPOSITORY_TOKEN',
    GEO_INFO_REPOSITORY_TOKEN = 'GEO_INFO_REPOSITORY_TOKEN',
    WEATHER_INFO_REPOSITORY_TOKEN = 'WEATHER_INFO_REPOSITORY_TOKEN',
    LOCATION_INFO_REPOSITORY_TOKEN = 'LOCATION_INFO_REPOSITORY_TOKEN',
    ENCRYPTION_REPOSITORY_TOKEN = 'ENCRYPTION_REPOSITORY_TOKEN',
    DIGITAL_PASSPORT_REPOSITORY_TOKEN = 'DIGITAL_PASSPORT_REPOSITORY_TOKEN',
    USER_STORY_LOG_REPOSITORY_TOKEN = 'USER_STORY_LOG_REPOSITORY_TOKEN',
    GROUP_QUEST_REPOSITORY_TOKEN = 'GROUP_QUEST_REPOSITORY_TOKEN',
}
