export enum TouriiBackendConstants {
    USER_REPOSITORY_TOKEN = 'USER_REPOSITORY_TOKEN',
    CONTEXT_PROVIDER_TOKEN = 'CONTEXT_PROVIDER_TOKEN',
    STORY_REPOSITORY_TOKEN = 'STORY_REPOSITORY_TOKEN',
    MODEL_ROUTE_REPOSITORY_TOKEN = 'MODEL_ROUTE_REPOSITORY_TOKEN',
    GEO_INFO_REPOSITORY_TOKEN = 'GEO_INFO_REPOSITORY_TOKEN',
    WEATHER_INFO_REPOSITORY_TOKEN = 'WEATHER_INFO_REPOSITORY_TOKEN',
}
