export enum TouriiBackendConstants {
	USER_REPOSITORY_TOKEN = "USER_REPOSITORY_TOKEN",
	CONTEXT_PROVIDER_TOKEN = "CONTEXT_PROVIDER_TOKEN",
	STORY_REPOSITORY_TOKEN = "STORY_REPOSITORY_TOKEN",
	QUEST_REPOSITORY_TOKEN = "QUEST_REPOSITORY_TOKEN",
}
