name: 🛠 Backend Task
description: Track API/database logic/backend logic tasks
title: "[BE] <Short title here>"
labels: ["backend", "type: task"]

body:

  - type: textarea
    id: description
    attributes:
      label: Task Description
      value: |
        ### Endpoint
        `<HTTP method> <URL>`  
        *(e.g., `POST /quests/:questId/group/join`)*
        
        ### Request
        ```json
        {
          "<key1>": "<value1>",
          "<key2>": "<value2>"
        }
        ```
        
        ### Response
        ```json
        {
          "<key1>": "<value1>",
          "<key2>": "<value2>"
        }
        ```
        
        ### Flow
        - Step 1: <Explain step>
        - Step 2: <Explain step>
        - Step 3: <Explain step>
        
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      value: |
        - [ ] Endpoint returns expected payload
        - [ ] Validations handled
        - [ ] Unit tests added (Optional)
        - [ ] Integration tests added (Optional)

  - type: checkboxes
    id: dependencies
    attributes:
      label: Dependencies
      options:
        - label: Requires schema migration
        - label: Needs frontend integration
        - label: Blocked by another issue
        - label: None
