# `passportTokenId` refers to the token_id stored in `user_onchain_item`
GET http://localhost:4000/web3/passport/1/linked-children
Content-Type: application/json
x-api-key: your-api-key-1
accept-version: 1.0.0

