POST http://localhost:4000/quests/update-task
Content-Type: application/json
x-api-key: your-api-key-1
accept-version: 1.0.0

{
    "taskId": "TSK202506-689f0d-141504-c54ed3-BAAA",
    "questId": "QST202506-f4869c-141501-dbae3f-BAAA",
    "taskTheme": "STORY",
    "taskType": "ANSWER_TEXT",
    "taskName": "Updated Task",
    "taskDesc": "Updated task description",
    "isUnlocked": true,
    "requiredAction": "Answer correctly",
    "groupActivityMembers": [],
    "selectOptions": [],
    "antiCheatRules": {},
    "magatamaPointAwarded": 10,
    "totalMagatamaPointAwarded": 10,
    "delFlag": false,
    "updUserId": "admin"
}
