POST http://localhost:4000/routes/create-tourist-spot/MRT202505-9a6e71-131928-c222c2-CAAA
Content-Type: application/json
x-api-key: your-api-key-2       
accept-version: 1.0.0

{
    "storyChapterId": "SCT202505-06dd86-131927-ec6094-BAAA",
    "touristSpotName": "二宮八幡社(緒方三社)",
    "touristSpotDesc": "Ninomiyahachimansha, over 800 years old and nestled on a forested hillside, was established by the noble warrior Ogata No Saburo Koreyoshi during the late Heian Period. Koreyoshi, a key figure in the Kamakura shogunate's establishment and linked to the serpent deity Oodamaki of Anamori Shrine, is celebrated for founding three shrines where his arrows landed, including Ninomiya Hachiman.\r\rThe region, known for its water abundance and rice cultivation, celebrates the Ogata Sansha Kawagoe-shi Matsuri in honor of water and harvest. The festival's centerpiece is the Kawagoe Festival, involving three shrines—Ichinomiya, Ninomiya, and Sannomiya—dedicated to divine figures from Japanese imperial history. It's famous for the ceremonial parade of portable shrines, especially the daring river crossing to Ninomiya Shrine, embodying a storied tradition observed around lunar mid-October.",
    "bestVisitTime": "9:00 am",
    "touristSpotHashtag": ["#Shrine", " #SpiritualSite"],
    "imageSet": {
        "main": "/image/touriiverse/bungo-ono/chapter2.png",
        "small": [
            "/image/model-route/1/ninomiya/1.jpg",
            "/image/model-route/1/ninomiya/2.jpg",
            "/image/model-route/1/ninomiya/3.jpg"
        ]
    }
}