POST http://localhost:4000/routes/create-model-route
Content-Type: application/json
x-api-key: your-api-key-2       
accept-version: 1.0.0


{
    "storyId": "STO202505-a26441-292305-c178d6-BAAA",
    "routeName": "The Sloth Route",
    "region": "Bungo Ono",
    "regionDesc": "Bungo Ono is a region in the world of Tourii. It is a region that is known for its beautiful nature and culture. It is a region that is known for its beautiful nature and culture.",
    "recommendation": [
        "Ideal for First Time Visitors",
        "A good mix of nature and culture",
        "Local Food"
    ],
    "touristSpotList": [
        {
            "storyChapterId": "SCT202505-2b167e-292250-fcec15-CAAA",
            "touristSpotName": "Ninomiya Shrine",
            "touristSpotDesc": "Ninomiya Shrine is a shrine in the world of Tourii. It is a shrine that is known for its beautiful nature and culture. It is a shrine that is known for its beautiful nature and culture.",
            "bestVisitTime": "9:00 am",
            "touristSpotHashtag": ["#Shrine", "#SpiritualSite"],
            "imageSet": {
                "main": "/image/touriiverse/bungo-ono/chapter2.png",
                "small": [
                    "/image/model-route/1/ninomiya/1.jpg",
                    "/image/model-route/1/ninomiya/2.jpg",
                    "/image/model-route/1/ninomiya/3.jpg"
                ]
            }
        }
    ]
}
