### Get All Model Routes
GET http://localhost:4000/routes
x-api-key: your-api-key-2       
accept-version: 1.0.0
Content-Type: application/json 

###

### Get Model Route by ID
GET http://localhost:4000/routes/MRT202505-92d614-292251-d58981-BAAA
x-api-key: your-api-key-2       
accept-version: 1.0.0
Content-Type: application/json

###

### Get Location Information
GET http://localhost:4000/locations/info?query=EboshiPark&address=Onomachi Fujikita, Bungoono, Oita 879-6442
x-api-key: your-api-key-2       
accept-version: 1.0.0
Content-Type: application/json 

###

### Get Tourist Spots by Story Chapter ID
GET http://localhost:4000/routes/tourist-spots/SCT202506-123456-abcdef
x-api-key: your-api-key-2
accept-version: 1.0.0
Content-Type: application/json

###

### Delete Model Route
DELETE http://localhost:4000/routes/MRT202506-654321-fedcba-CAAA
x-api-key: your-api-key-2
accept-version: 1.0.0

###

### Delete Tourist Spot
DELETE http://localhost:4000/routes/tourist-spots/TST202506-0fedcb-321987-DAAA
x-api-key: your-api-key-2
accept-version: 1.0.0

###