export enum TouriiOnchainConstants {
    SAILS_CALLS_REPOSITORY_TOKEN = 'SAILS_CALLS_REPOSITORY_TOKEN',
    JWT_REPOSITORY_TOKEN = 'JWT_REPOSITORY_TOKEN',
    ENCRYPTION_REPOSITORY_TOKEN = 'ENCRYPTION_REPOSITORY_TOKEN',
}
