export enum TouriiOnchainConstants {
    SAILS_CALLS_REPOSITORY_TOKEN = 'SAILS_CALLS_REPOSITORY_TOKEN',
    JWT_REPOSITORY_TOKEN = 'JWT_REPOSITORY_TOKEN',
    ENCRYPTION_REPOSITORY_TOKEN = 'ENCRYPTION_REPOSITORY_TOKEN',
    PASSPORT_METADATA_REPOSITORY_TOKEN = 'PASSPORT_METADATA_REPOSITORY_TOKEN',
    CONTEXT_PROVIDER_TOKEN = 'CONTEXT_PROVIDER_TOKEN',
    USER_REPOSITORY_TOKEN = 'USER_REPOSITORY_TOKEN',
    R2_STORAGE_REPOSITORY_TOKEN = 'R2_STORAGE_REPOSITORY_TOKEN',
}
