/**
 * Japanese address parsing constants
 * Contains prefecture and city mappings for address parsing
 */

// Complete list of Japanese prefectures in multiple forms
export const PREFECTURE_MAPPING: Record<string, string> = {
    // Hokkaido
    hokkaido: 'Hokkaido',
    北海道: 'Hokkaido',

    // Tohoku
    aomori: 'Aomori',
    青森: 'Aomori',
    iwate: 'Iwate',
    岩手: 'Iwate',
    miyagi: 'Miyagi',
    宮城: 'Miyagi',
    akita: 'Akita',
    秋田: 'Akita',
    yamagata: 'Yamagata',
    山形: 'Yamagata',
    fukushima: 'Fukushima',
    福島: 'Fukushima',

    // Kanto
    ibaraki: 'Ibaraki',
    茨城: 'Ibaraki',
    tochigi: 'Tochigi',
    栃木: 'Tochigi',
    gunma: 'Gunma',
    群馬: 'Gunma',
    saitama: 'Saitama',
    埼玉: 'Saitama',
    chiba: 'Chiba',
    千葉: 'Chiba',
    tokyo: 'Tokyo',
    東京: 'Tokyo',
    kanagawa: 'Kanagawa',
    神奈川: 'Kanagawa',

    // Chubu
    niigata: 'Niigata',
    新潟: 'Niigata',
    toyama: 'Toyama',
    富山: 'Toyama',
    ishikawa: 'Ishikawa',
    石川: 'Ishikawa',
    fukui: 'Fukui',
    福井: 'Fukui',
    yamanashi: 'Yamanashi',
    山梨: 'Yamanashi',
    nagano: 'Nagano',
    長野: 'Nagano',
    gifu: 'Gifu',
    岐阜: 'Gifu',
    shizuoka: 'Shizuoka',
    静岡: 'Shizuoka',
    aichi: 'Aichi',
    愛知: 'Aichi',

    // Kansai/Kinki
    mie: 'Mie',
    三重: 'Mie',
    shiga: 'Shiga',
    滋賀: 'Shiga',
    kyoto: 'Kyoto',
    京都: 'Kyoto',
    osaka: 'Osaka',
    大阪: 'Osaka',
    hyogo: 'Hyogo',
    兵庫: 'Hyogo',
    nara: 'Nara',
    奈良: 'Nara',
    wakayama: 'Wakayama',
    和歌山: 'Wakayama',

    // Chugoku
    tottori: 'Tottori',
    鳥取: 'Tottori',
    shimane: 'Shimane',
    島根: 'Shimane',
    okayama: 'Okayama',
    岡山: 'Okayama',
    hiroshima: 'Hiroshima',
    広島: 'Hiroshima',
    yamaguchi: 'Yamaguchi',
    山口: 'Yamaguchi',

    // Shikoku
    tokushima: 'Tokushima',
    徳島: 'Tokushima',
    kagawa: 'Kagawa',
    香川: 'Kagawa',
    ehime: 'Ehime',
    愛媛: 'Ehime',
    kochi: 'Kochi',
    高知: 'Kochi',

    // Kyushu
    fukuoka: 'Fukuoka',
    福岡: 'Fukuoka',
    saga: 'Saga',
    佐賀: 'Saga',
    nagasaki: 'Nagasaki',
    長崎: 'Nagasaki',
    kumamoto: 'Kumamoto',
    熊本: 'Kumamoto',
    oita: 'Oita',
    大分: 'Oita',
    miyazaki: 'Miyazaki',
    宮崎: 'Miyazaki',
    kagoshima: 'Kagoshima',
    鹿児島: 'Kagoshima',
    okinawa: 'Okinawa',
    沖縄: 'Okinawa',
};

// Common city names that might be confused with prefectures
export const MAJOR_CITIES: Record<string, string> = {
    shibuya: 'Tokyo',
    渋谷: 'Tokyo',
    shinjuku: 'Tokyo',
    新宿: 'Tokyo',
    harajuku: 'Tokyo',
    原宿: 'Tokyo',
    ginza: 'Tokyo',
    銀座: 'Tokyo',
    akihabara: 'Tokyo',
    秋葉原: 'Tokyo',
    tsukiji: 'Tokyo',
    築地: 'Tokyo',
    roppongi: 'Tokyo',
    六本木: 'Tokyo',
    ikebukuro: 'Tokyo',
    池袋: 'Tokyo',
    ueno: 'Tokyo',
    上野: 'Tokyo',
    asakusa: 'Tokyo',
    浅草: 'Tokyo',
    'chuo city': 'Tokyo',
    中央区: 'Tokyo',
    minato: 'Tokyo',
    港区: 'Tokyo',
    yokohama: 'Kanagawa',
    横浜: 'Kanagawa',
    kawasaki: 'Kanagawa',
    川崎: 'Kanagawa',
    kobe: 'Hyogo',
    神戸: 'Hyogo',
    sendai: 'Miyagi',
    仙台: 'Miyagi',
    sapporo: 'Hokkaido',
    札幌: 'Hokkaido',
    'fukuoka city': 'Fukuoka',
    福岡市: 'Fukuoka',
    bungoono: 'Oita',
    豊後大野: 'Oita',
};
